import { mockOffers,marketCategories } from './market-data.js';
import { photos, destinations } from './data.js';

export function marketMarkup({trip,state,ico,safe,yen,formatDate}){
  const hasTrip=!!trip.id;
  const tripImage=destinations.find(item=>item.name===trip.destination)?.image||photos.hotel;
  const category=state.marketCategory||'all';
  const query=(state.marketSearch||'').toLowerCase();
  const filtered=mockOffers.filter(o=>(category==='all'||category==='orders'||category==='saved'&&state.marketSaved.includes(o.id)||o.category===category)&&(!query||`${o.title}${o.subtitle}${o.kind}${o.tags.join('')}`.toLowerCase().includes(query)));
  filtered.sort((a,b)=>state.marketSort==='price-asc'?a.price-b.price:state.marketSort==='price-desc'?b.price-a.price:0);
  const all=category==='orders'?[]:filtered;
  return `<main class="market-page"><section class="market-hero"><div class="market-hero-copy"><span class="market-kicker">XIANGYE / TRAVEL MARKET</span><h1>机票酒店<span> · </span><br/>当地玩乐。</h1><p>${hasTrip?`正在参考 ${safe(trip.destination)} 行程。下方为通用演示方案，并非按目的地筛选的真实库存。`:'先浏览交通、住宿和当地体验的演示方案；创建行程后可带入日期与目的地。'}实际库存与价格请到服务平台核验。</p><div class="market-hero-search">${hasTrip?`<span>${ico('pin',17)} ${safe(trip.origin)} → ${safe(trip.destination)}</span><i></i><span>${ico('calendar',17)} ${formatDate(trip.start)} — ${formatDate(trip.end)}</span><i></i><span>${ico('user',17)} ${trip.party} 人</span>`:`<button class="market-plan-link" data-nav="plan">先规划行程 ${ico('arrow',16)}</button>`}</div></div><div class="market-hero-image" style="background-image:url('${tripImage}')"><span>THIS JOURNEY IS YOURS</span></div></section>
    <div class="market-notice">${ico('spark',16)} <span>本页为可交互的预订演示。商品、报价与订单均为模拟，不会产生支付或真实预订。</span><button data-nav="plan">返回行程 ${ico('arrow',15)}</button></div>
    <div class="market-section-title"><div><span>EXPLORE THE JOURNEY</span><h2>旅行所需，一站浏览</h2><p>按类别探索、收藏、查看详情，还可以试走一遍下单流程。</p></div><span class="market-count">${category==='orders'?state.marketOrders.length:all.length} 个${category==='orders'?'模拟订单':'展示方案'}</span></div>
    <div class="market-categories">${marketCategories.map(c=>`<button data-market-category="${c.id}" class="${category===c.id?'active':''}">${ico(c.icon,18)} ${c.name}${c.id==='orders'&&state.marketOrders.length?` <b>${state.marketOrders.length}</b>`:''}</button>`).join('')}</div>
    ${category==='orders'?ordersMarkup({state,ico,safe,yen}):`<div class="market-filter"><form id="marketSearchForm">${ico('search',18)}<input name="query" value="${safe(state.marketSearch||'')}" placeholder="搜索住宿、体验或出行方案"/><button>搜索</button></form><label>排序<select id="marketSort"><option value="featured" ${state.marketSort==='featured'?'selected':''}>默认展示</option><option value="price-asc" ${state.marketSort==='price-asc'?'selected':''}>模拟价格从低到高</option><option value="price-desc" ${state.marketSort==='price-desc'?'selected':''}>模拟价格从高到低</option></select></label></div><div class="market-grid">${all.length?all.map(o=>offerCard({offer:o,state,ico,safe,yen})).join(''):'<div class="market-empty">暂时没有匹配的演示方案，试试其他关键词或类别。</div>'}</div>`}
    ${category==='orders'?'':`<section class="market-places"><div><span>REAL PLACES / 地点核验</span><h2>想先看看真实位置？</h2><p>搜索地图地点，核对地址后可加入旅行计划。商品仍需在服务平台确认。</p></div><form id="marketPlaceForm"><input name="query" value="${safe(state.marketPlaceQuery)}" placeholder="搜索${safe(trip.destination||'全国')}的酒店、景点或活动场馆" maxlength="80" required/><button ${state.marketPlaceBusy?'disabled':''}>${state.marketPlaceBusy?'查询中…':'搜索地图'} ${ico('search',16)}</button></form>${state.marketPlaceError?`<p class="market-place-error">${safe(state.marketPlaceError)}</p>`:''}${state.marketPlaces.length?`<div class="market-place-results">${state.marketPlaces.map((p,i)=>`<article><span>${ico('pin',17)}</span><div><strong>${safe(p.name)}</strong><small>${safe(p.address)} · ${safe(p.source)}</small></div>${hasTrip?`<button data-market-place-add="${i}">加入行程</button>`:`<button data-nav="plan">先创建行程</button>`}</article>`).join('')}</div>`:''}</section>`}
    <section class="market-guide"><div><span>01</span><strong>先挑方向</strong><p>根据行程日期和地点，找到合适的类别。</p></div><div><span>02</span><strong>再看细节</strong><p>对比交通、住宿和体验的使用条件。</p></div><div><span>03</span><strong>真实预订去平台</strong><p>出发前核对实时库存、实付价和退改政策。</p></div></section>
  </main>`;
}

function offerCard({offer:o,state,ico,safe,yen}){
  return `<article class="market-card"><div class="market-card-image" style="background-image:url('${o.image}')"><span class="market-card-kind">${safe(o.kind)}</span><button data-market-save="${safe(o.id)}" class="${state.marketSaved.includes(o.id)?'saved':''}" aria-label="${state.marketSaved.includes(o.id)?'取消收藏':'收藏'}${safe(o.title)}">${ico('heart',17)}</button></div><div class="market-card-body"><span class="market-card-sim">演示方案 · 模拟价格</span><h3>${safe(o.title)}</h3><p>${safe(o.subtitle)}</p><div class="market-card-tags">${o.tags.map(t=>`<span>${safe(t)}</span>`).join('')}</div><div class="market-card-footer"><div><small>模拟参考</small><strong>${yen(o.price)}<em> / ${safe(o.unit)}</em></strong></div><button data-market-offer="${safe(o.id)}">查看详情 ${ico('arrow',16)}</button></div></div></article>`;
}

function ordersMarkup({state,ico,safe,yen}){
  if(!state.marketOrders.length)return `<div class="market-orders-empty">${ico('ticket',32)}<h3>还没有模拟订单</h3><p>选择一个演示方案，可以体验核对行程和确认订单的完整流程。</p><button data-market-category="all">去逛逛 ${ico('arrow',16)}</button></div>`;
  return `<div class="market-orders">${state.marketOrders.map(o=>`<article class="market-order"><div><span>模拟订单 · ${safe(o.createdAt)}</span><h3>${safe(o.title)}</h3><p>${safe(o.city)} · ${safe(o.date)} · ${o.guests} 人</p></div><div><strong>${yen(o.total)}</strong><small>不会扣款</small></div><button data-market-cancel="${safe(o.id)}">取消演示订单</button></article>`).join('')}</div>`;
}

export function marketOfferModal({offer:o,trip,ico,safe,yen}){
  if(!o)return '';
  return `<div class="market-modal-cover" style="background-image:url('${o.image}')"><span>演示方案 · ${safe(o.kind)}</span></div><div class="modal-heading"><span class="eyebrow">TRAVEL MARKET / ${safe(o.kind)}</span><h2>${safe(o.title)}</h2><p>${safe(o.subtitle)}</p></div><div class="market-modal-tags">${o.tags.map(t=>`<span>${safe(t)}</span>`).join('')}</div><div class="detail-facts"><div><span>参考行程</span><strong>${trip.id?`${safe(trip.origin)} → ${safe(trip.destination)} · ${trip.party} 人`:'尚未创建行程'}</strong></div><div><span>参考日期</span><strong>${trip.id?`${safe(trip.start)} — ${safe(trip.end)}`:'创建行程后带入日期'}</strong></div><div><span>模拟参考价</span><strong>${yen(o.price)} / ${safe(o.unit)}</strong></div></div><p class="market-modal-description">${safe(o.description)}</p><div class="modal-actions"><button class="outline-btn" data-action="closeModal">继续浏览</button>${trip.id?`<button class="primary-btn" data-market-begin="${safe(o.id)}">体验模拟预订 ${ico('arrow',16)}</button>`:`<button class="primary-btn" data-nav="new">先创建行程 ${ico('arrow',16)}</button>`}</div><a class="market-real-link" href="${o.link}" target="_blank" rel="noopener noreferrer">去服务平台核验真实商品 ${ico('arrow',15)}</a>`;
}

export function marketCheckoutModal({offer:o,trip,ico,safe,yen}){
  if(!o)return '';
  return `<div class="modal-heading"><span class="eyebrow">DEMO CHECKOUT</span><h2>核对模拟订单</h2><p>这一步只会生成浏览器里的演示记录，不会支付或预订。</p></div><div class="market-checkout-product"><span>${safe(o.kind)}</span><strong>${safe(o.title)}</strong><small>${safe(trip.destination)} · 模拟参考价 ${yen(o.price)} / ${safe(o.unit)}</small></div><form id="marketCheckoutForm" class="modal-form"><input type="hidden" name="offerId" value="${safe(o.id)}"/><label>体验日期<input name="date" type="date" value="${safe(trip.start)}" min="${safe(trip.start)}" max="${safe(trip.end)}" required/></label><label>人数 / 间夜<input name="guests" type="number" min="1" max="8" value="${Math.min(trip.party,8)}" required/></label><div class="market-checkout-total"><span>模拟合计 <small>以最终平台报价为准</small></span><strong>${yen(o.price*Math.min(trip.party,8))}</strong></div><button class="primary-btn">确认生成模拟订单</button></form>`;
}
